slither:
	slitherin . --slither > slither_report.md

slitherin:
	slitherin . --pess > slitherin_report.md

aderyn:
	aderyn . -o aderyn_report.md

myth:
	myth analyze $(path) --solc-json myth.config.json -o markdown > mythril_report.md

